base_url = "https://jason.locklin.science"
title = "Jason Locklin"
description = "Research, data, and education."
theme = "terminus"
compile_sass = true
generate_feeds = true
author = "Jason Locklin"

taxonomies = [
    { name = "tags",       feed = true },
    { name = "categories", feed = true },
]

[markdown]
render_emoji = false
bottom_footnotes = true
lazy_async_image = true
github_alerts = true

[markdown.highlighting]
style = "inline"
theme = "monokai"

[extra]
favicon_emoji = "📊"
feed_icon = true
layout = "center"
show_default_author = false
stylesheets = ["css/custom.css"]

main_menu = [
    { name = "Top",      url = "/",                   trailing_slash = false },
    { name = "Blog",     url = "posts",               trailing_slash = true  },
    { name = "R",        url = "tags/r",              trailing_slash = true  },
    { name = "Research", url = "categories/research", trailing_slash = true  },
    { name = "Benchtop", url = "categories/benchtop", trailing_slash = true  },
    { name = "Soapbox",  url = "categories/soapbox",  trailing_slash = true  },
    { name = "Links",    url = "links",               trailing_slash = true  },
    { name = "Uses",     url = "uses",                trailing_slash = true  },
    { name = "Now",      url = "now",                 trailing_slash = true  },
]

copyright = "© $YEAR Jason Locklin, PhD"

socials = [
    { name = "email",  url = "mailto:Jason@Locklin.science" },
    { name = "github", url = "https://github.com/jasonlocklin" },
]

[extra.responsive_images]
widths = [640, 784, 1280]
fallback_width = 784
