baseurl = "http://jason.locklin.science"
title = "Jason Locklin, PhD."
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Jason Locklin"
  fingerprint = "PGP: D532 9E35 173B 5698 0F32  F96A 5454 D302 327E BCBE"
  info = "Research, Data Science, Community and Equity"
  description = "Jason Locklin's academic/professional homepage"
  keywords = "Data Science, Research, Equity"
  avatarurl = "images/profile1.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

 customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "EMAIL"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 1
  url = "mailto:jason@locklin.science"


[[params.social]]
  name = "WRDSB"
  icon = "fa-solid fa-building fa-2x"
  weight = 1
  url = "about/"

[[params.social]]
  name = "R-Project"
  icon = "fa-brands fa-r-project fa-2x"
  weight = 1
  url = "posts/r/"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/JasonLocklin/"

[[params.social]]
  name = "Google Scholar"
  icon = "fa-brands fa-google-scholar fa-2x"
  weight = 3
  url = "https://scholar.google.ca/citations?user=ZarRn1wAAAAJ&hl=en&oi=ao"

[[params.social]]
  name = "orcid"
  icon = "fa-brands fa-orcid fa-2x"
  weight = 4
  url = "https://orcid.org/0000-0001-7777-9065"

[[params.social]]
  name = "ResearchGate"
  icon = "fa-brands fa-researchgate fa-2x"
  weight = 4
  url = "https://www.researchgate.net/profile/Jason-Locklin-4"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
